docs(readme): new logo and header
ipfs/kubo pull request #10088
Opened 2023-08-18 15:38 UTC by lidel

2023-08-18 22:01 UTC, hacdias approved these changes
🎉

2023-08-18 22:17 UTC, Jorropo requested changes
Disapointed, 0/20.

2023-08-18 22:17 UTC, Jorropo commented on README.md
> +<img src="https://user-images.githubusercontent.com/157609/250148884-d6d12db8-fdcf-4be3-8546-2550b69845d8.png" alt="Kubo logo" title="Kubo logo" width="200">
```suggestion
<img src="https://ipfs.io/ipfs/QmTtCH31LdGV4LjRm5FNmnw6hUwZq1Z1YXtjeNKHBeaRcQ/kubo-logo.png" alt="Kubo logo" title="Kubo logo" width="200">
```
```
curl https://user-images.githubusercontent.com/157609/250148884-d6d12db8-fdcf-4be3-8546-2550b69845d8.png | ipfs add --raw-leaves --stdin-name kubo-logo.png -w
```

2023-08-18 22:20 UTC, Jorropo commented on README.md
> +<img src="https://user-images.githubusercontent.com/157609/250148884-d6d12db8-fdcf-4be3-8546-2550b69845d8.png" alt="Kubo logo" title="Kubo logo" width="200">
Also, I don't really care but don't we have an SVG of the logo ?

2023-08-21 03:11 UTC, BigLep approved these changes

2023-08-22 09:20 UTC, merged