featrue: Include go-ds-pebble as built-in plugin
ipfs/kubo pull request #10367
Opened 2024-03-12 09:23 UTC by guojidan

closed: #10347 

I have tested it locally, It seems to be working properly 🤔

2024-03-25 13:07 UTC, lidel requested changes
Thank you for taking a stab at this @guojidan.
Are you able to add tests in similar to ones we have for `badgerds` in

- test/sharness/t0060-daemon.sh
- test/sharness/t0025-datastores.sh 

?

2024-03-25 13:07 UTC, lidel commented on docs/datastores.md
> +```
@hsanjuan I know pebble is used by default in IPFS Cluster, and there is a lot of custom configuration in https://github.com/ipfs-cluster/ipfs-cluster/blob/v1.0.8/datastore/pebble/config.go#L25-L70

Two questions:
1. Does it make sense to expose them all via config here (as optional, use only when set)
2. For implicit defaults, should we use defaults from pebble, or ones from ipfs-cluster?

2024-03-25 13:22 UTC, guojidan commented
I will do this in the next few days

2024-07-30 16:49 UTC, lidel commented
Triage question: @guojidan will you have interest and time to work on this, or is it ok for someone else to pick up the pebble work?

2024-08-06 16:15 UTC, lidel commented
@guojidan no problem!  @gammazero will pick this up after we are done with more pressing stuff. 

closing this PR, we will continue in #10347 + new one.

2024-08-06 16:15 UTC, closed without merging