feat: use ipfs-webui@4.3.1
ipfs/kubo pull request #10523
Opened 2024-09-23 16:34 UTC by SgtPooki

2024-09-23 17:47 UTC, lidel requested changes
Ok, I think things with https://github.com/ipfs/ipfs-webui/issues/2266 are worse than I thought, it IS a regression because local Kubo  is not used at all by IPLD Explorer.


Just try opening IPLD Explorer's  Wikipedia example on empty browser profile (without Helia caching a block):


| v4.3.0 only hits local Kubo | v4.3.1 hits random gateways and not local Kubo  | 
| ---- | ---- |
| ![old-2024-09-23_19-42](https://github.com/user-attachments/assets/8f0c61f5-4010-4ef9-b300-aaaf9162ba8f) | ![new-2024-09-23_19-44](https://github.com/user-attachments/assets/f7113021-a75c-4272-8b9f-ef2f7cedb5e3) |

So we can't update ipfs-webui without fixing https://github.com/ipfs/ipfs-webui/issues/2266 first.

2024-09-23 17:50 UTC, SgtPooki commented
I will work on that bug asap

2024-09-24 18:52 UTC, lidel commented on core/corehttp/webui.go
> +const WebUIPath = "/ipfs/bafybeideglc722hiwhsy4kiyl2fivf5lr6wozy2iuixtgzkvl3v4hasaty" // v4.3.1
```suggestion
const WebUIPath = "/ipfs/bafybeif6abowqcavbkz243biyh7pde7ick5kkwwytrh7pd2hkbtuqysjxy" // v4.3.2
```

2024-09-24 18:54 UTC, lidel approved these changes
switched to [v4.3.2](https://github.com/ipfs/ipfs-webui/releases/tag/v4.3.2) lgtm, thank you @SgtPooki

2024-09-24 21:26 UTC, merged