chore: update to boxo without goprocess
ipfs/kubo pull request #10567
Opened 2024-10-31 01:24 UTC by gammazero

2024-11-08 15:20 UTC, hsanjuan approved these changes

2024-11-18 20:08 UTC, lidel requested changes
I think I've tracked down why prometheus metrics tests were failing.


When manually starting `ipfs daemon`, it produces errors:

```
2024-11-18T21:07:43.009+0100	ERROR	metrics-prometheus	go-metrics-prometheus@v0.0.3/binding.go:61	Registering prometheus collector, name: <no-scope>_pending_tasks, error: descriptor Desc{fqName: "<no-scope>_pending_tasks", help: "Total number of pending tasks", constLabels: {}, variableLabels: {}} is invalid: "<no-scope>_pending_tasks" is not a valid metric name
2024-11-18T21:07:43.013+0100	ERROR	metrics-prometheus	go-metrics-prometheus@v0.0.3/binding.go:61	Registering prometheus collector, name: <no-scope>_active_tasks, error: descriptor Desc{fqName: "<no-scope>_active_tasks", help: "Total number of active tasks", constLabels: {}, variableLabels: {}} is invalid: "<no-scope>_active_tasks" is not a valid metric name
2024-11-18T21:07:43.013+0100	ERROR	metrics-prometheus	go-metrics-prometheus@v0.0.3/binding.go:61	Registering prometheus collector, name: <no-scope>_pending_block_tasks, error: descriptor Desc{fqName: "<no-scope>_pending_block_tasks", help: "Total number of pending blockstore tasks", constLabels: {}, variableLabels: {}} is invalid: "<no-scope>_pending_block_tasks" is not a valid metric name
2024-11-18T21:07:43.013+0100	ERROR	metrics-prometheus	go-metrics-prometheus@v0.0.3/binding.go:61	Registering prometheus collector, name: <no-scope>_active_block_tasks, error: descriptor Desc{fqName: "<no-scope>_active_block_tasks", help: "Total number of active blockstore tasks", constLabels: {}, variableLabels: {}} is invalid: "<no-scope>_active_block_tasks" is not a valid metric name
```

Trying to kill `ipfs deamon` with ctrl+c produces panic, there seem to be goprocess still somewhere:

```
Run 'ipfs id' to inspect announced and discovered multiaddrs of this node.
panic: Process cannot add children after being closed

goroutine 1 [running]:
github.com/jbenet/goprocess.(*process).AddChild(0xc000c38d80, {0x3663ea8, 0xc001d1ab40})
	github.com/jbenet/goprocess@v0.1.4/impl-mutex.go:99 +0x24d
github.com/ipfs/kubo/cmd/ipfs/kubo.daemonFunc(0xc0003f0000, {0x6?, 0xc0000f0050?}, {0x2e15620, 0xc0004b40a0})
	github.com/ipfs/kubo/cmd/ipfs/kubo/daemon.go:515 +0x1aa8
github.com/ipfs/go-ipfs-cmds.(*executor).Execute(0x489a100?, 0xc0003f0000, {0x7ff5b2869578, 0xc0000c7c80}, {0x2e15620, 0xc0004b40a0})
	github.com/ipfs/go-ipfs-cmds@v0.14.0/executor.go:88 +0x126
github.com/ipfs/kubo/cmd/ipfs/kubo.tracingWrappedExecutor.Execute({{0x36337a0?, 0xc00028a078?}}, 0xc0003f0000, {0x7ff5b2869578, 0xc0000c7c80}, {0x2e15620, 0xc0004b40a0})
	github.com/ipfs/kubo/cmd/ipfs/kubo/start.go:375 +0x3eb
github.com/ipfs/go-ipfs-cmds/cli.Run({0x364f258?, 0xc0004434f0?}, 0x49faf20, {0xc000160000, 0x2, 0x2}, 0x6e0?, 0xc00012e028, 0xc00012e030, 0x33b6370, ...)
	github.com/ipfs/go-ipfs-cmds@v0.14.0/cli/run.go:137 +0x99c
github.com/ipfs/kubo/cmd/ipfs/kubo.Start(0x33b6370)
	github.com/ipfs/kubo/cmd/ipfs/kubo/start.go:213 +0x516
main.main()
	github.com/ipfs/kubo/cmd/ipfs/main.go:10 +0x1a
```

2024-11-19 05:08 UTC, gammazero commented
I updated this PR to a "fixed" version of boxo to fix the metrics registration issue. Another small fix in the daemon code to remove the panic on early ctrl-c before daemon ready.

The  change in boxo was to pass the context into the server decision engine. I would prefer not relying on long-lived contexts to do things like metrics registration.

2024-11-19 17:03 UTC, lidel approved these changes
Thanks, both issues are fixed, and helia-interop was fixed upstream.

Switched to commit from boxo main. I'm going to merge this so we have more time to catch issues (if any).

2024-11-19 17:04 UTC, merged