feat: Add CI for Spell Checking
ipfs/kubo pull request #10637
Opened 2024-12-20 20:20 UTC by youyyytrok

This pull request introduces a Continuous Integration (CI) workflow for detecting spelling mistakes using `codespell`. The following changes have been implemented:

- Added a GitHub Actions workflow for spell checking.
- Fixed all spelling mistakes detected by `codespell` throughout the repository.

These improvements enhance documentation and code readability while ensuring consistency across the codebase.

2025-01-15 02:02 UTC, lidel requested changes
Thank you @youyyytrok!

Before merging this we need to fix sharness tests (details inline)

2025-01-22 16:33 UTC, lidel approved these changes
Thanks! Let's merge and see how it goes.
We can always remove it if it causes CI failures more often than catching typos.

2025-01-22 16:38 UTC, lidel requested changes
Lol I spoke too soon :sweat_smile: – see comment below

2025-01-22 16:38 UTC, lidel commented on .github/workflows/spellcheck.yml
> +        run: pip install codespell
@youyyytrok  re-running the same CI job started failing: 
– https://github.com/ipfs/kubo/actions/runs/12788199550/job/36008198868#step:4:10

 I think this is due to codespell version not being pinned – any way we can control this so it does not break CI every time codespell updates rules?

2025-01-28 15:41 UTC, guillaumemichel commented
Triage notes:
* @youyyytrok  We would like to keep the CI all green even if there are typos, could you please update the PR to use https://github.com/codespell-project/actions-codespell?tab=readme-ov-file#parameter-only_warn

2025-01-30 08:29 UTC, guillaumemichel commented
It seems that ignoring `./doc/AUTHORS` didn't work. See [here](https://github.com/ipfs/kubo/actions/runs/13048036205/job/36402538030?pr=10637#step:5:34). @youyyytrok could you find out why?

2025-01-30 16:49 UTC, guillaumemichel approved these changes

2025-01-30 16:50 UTC, merged