chore: update to go-log@v2
ipfs/kubo pull request #8765
Opened 2022-03-04 20:58 UTC by schomatis

Closes https://github.com/ipfs/go-ipfs/issues/8753.

2022-03-04 20:59 UTC, schomatis commented on core/corehttp/logs.go
> +			}()
Blocking: need help.

2022-03-04 20:59 UTC, schomatis commented on core/corehttp/logs.go
> +			log.Debugf("log API client connected")
Blocking: need help.

2022-04-07 16:15 UTC, BigLep commented
2022-04-07: we need to see if this has been superseded by go-libp2p work.

2022-04-13 03:08 UTC, Jorropo requested changes

2022-04-13 03:08 UTC, Jorropo commented on core/corehttp/logs.go
> +					default:
That code is a potential CPU spinner if you have a non blocking reader being returned. (which currently is not the case, currently this is an `io.Pipe` which blocks if there is no data).

Just one more reason to make the correct thing (either just enroll it in the log framework, or make a custom asynchronous buffering thing and enroll that).

2022-04-13 03:13 UTC, Jorropo commented
@schomatis you should also rebase on master, a few things have changed, but AFAIK not the main ***blocking*** point.

2022-04-21 14:53 UTC, BigLep commented
@schomatis : are you going to make the corresponding change/improvement in go-lobv2?

2022-04-21 18:35 UTC, schomatis commented
@BigLep I'm confused on exactly what those changes should be. That's why I requested an issue to be created with the scoped changes needed to land this PR (if those are indeed a blocker here; I didn't completely understood the feedback here).

2022-04-21 19:45 UTC, Jorropo commented
Ok, I'll open an issue on go-log

2022-04-26 14:42 UTC, BigLep commented
2022-04-26 conversation: 
1. For 0.13: do nothing (in the release notes for 0.13, "if you were using log-tail for certain things, you'll need to look at the daemon input.  Previously we had some output in daemon logs and some log-tail.")
2. For 0.14 we're going to make log-tail work as desired.

2022-04-26 15:20 UTC, schomatis commented
@BigLep Note that `ipfs log tail` can be fixed pretty easily, independent of the entire "switch the whole code base to log@v2". It's just the file diff https://github.com/ipfs/go-ipfs/pull/8765/files#diff-8ecc58f41eaa3971752dc974dd21fd9c1ecfdac1c15e9e9c40dc6fa4283a8d4e.

That can land in the next release if desired.

2022-07-26 15:24 UTC, BigLep commented
@Jorropo : is there an issue in https://github.com/ipfs/go-log to improve things there?

2025-05-16 21:02 UTC, lidel commented
Continued in https://github.com/ipfs/kubo/pull/10801

2025-05-16 21:02 UTC, closed without merging