feat(gateway): .tar response format
ipfs/kubo pull request #9029
Opened 2022-06-09 14:01 UTC by hacdias

Maybe #7746.

- [ ] Maybe .tar.gz
- [ ] Tests
- [ ] Needs spec as per (https://github.com/ipfs/go-ipfs/issues/7746#issuecomment-1150493574), investigte

2022-06-09 19:25 UTC, lidel requested changes
Thank you for driving this @hacdias

Looks sensible, next steps:

- Update `http-gateways/PATH_GATEWAY.md` specs
   -  Rationale: downloading UnixFS directory as TAR massively increases utility of  gateways in use cases where CAR is not necessary, so this should be part of the spec 
    - PR against my PR (https://github.com/ipfs/specs/pull/283) for now
- needs sharness test that downloads a directory as TAR  and saves it to disk (curl piped to tar command should be enough)

2022-06-09 19:25 UTC, lidel commented on core/corehttp/gateway_handler_tar.go
> +	w.Header().Set("X-Content-Type-Options", "nosniff") // no funny business in the browsers :^)
TAR is not impacted by the same block ordering issues as CAR, so we don't need to be as strict here –  ideally, TAR should follow the same Cache-Control rules as  ` serveFile`:

```suggestion
	w.Header().Set("Content-Type", "application/x-tar")
```

2022-06-09 19:25 UTC, lidel commented on core/corehttp/gateway_handler_tar.go
> +	// modtime := addCacheControlHeaders(w, r, contentPath, resolvedPath.Cid())
Below should be ok, but for it to set correct Etag, we need update the way we create Etag suffix in: 

https://github.com/ipfs/go-ipfs/blob/1a3b41c23be70de3ea9273c283845025bbb59b44/core/corehttp/gateway_handler.go#L876-L877

```suggestion
	// Set Cache-Control and read optional Last-Modified time
	modtime := addCacheControlHeaders(w, r, contentPath, resolvedPath.Cid())
```

2022-06-10 12:26 UTC, hacdias commented
@lidel thanks for the review. I added two tests (not sure if on the right file). This only adds support for `.tar`. Should we also add `.tar.gz`?

2022-06-18 03:55 UTC, kubanomaha approved these changes

2022-09-01 22:29 UTC, lidel commented
(I have unfinished review of this pending and some local test code, re-assigning to myself, as some notes for implementers  need to be bubbled up to IPIP)

2022-09-14 18:43 UTC, BigLep commented on test/sharness/t0110-gateway.sh
> +'
We're testing the `?format=tar` option but what about the `Accept` HTTP header?

2022-10-04 14:54 UTC, hacdias commented
To test the security concern raised by @lidel in [this comment](https://github.com/ipfs/specs/pull/288#discussion_r983835673) regarding overwriting files by having custom relative paths inside a custom made UnixFS DAG, I... built my own DAG that tries to exploit that same issue.

CID: `bafybeieq5yvoaqyrfvyiwqvi7hqhi54hyqhyatkn3pgbjxylpxdm5cj5t4`

```
└─dir
  │ file
  │ ../../../malicious-file		<- Would rewrite a file outside the root directory
└─../../malicious-dir			<- Would rewrite a directory outside the root directory
  │ file 
```

I just pushed a WIP version of a "Base Dir TAR Writer"  which is essentially a copy of the [TAR Writer](https://github.com/ipfs/go-ipfs-files/blob/master/tarwriter.go) in `go-ipfs-files`. The difference is that we always ensure that all files are under a certain base directory.

```go
	if !strings.HasPrefix(fpath, w.baseDir) {
		fpath = strings.Replace(fpath, ".", "", -1)
		fpath = strings.Replace(fpath, "..", "", -1)
		fpath = path.Join(w.baseDir, fpath)
	}
```

It does what it is supposed to do (only tested locally, no testcase). Some things I'm still unhappy with:

1. We do not keep the intended file tree of the directory. Since all files that would fall outside of the base directory are now at the root of the base directory, the tree isn't maintained. A way to maintain the structure would be to traverse the entire file tree first, and "calculate" the correct root directory in order to preserve the entire file tree.
	- But maybe this would take more valuable processing time?
	- One of the reasons why I did not write a test case yet because it will change slightly depending on whether we want to preserve the whole tree or just truncate the odd files to the root directory.
2. It is just a copy paste of the original TAR Writer with 5 lines added. There may be an easier way to reuse the original code that I can't see right now.

**Note** that the original TAR Writer is also used in `ipfs get --archive`, which means that that command also suffers from the same security 'concern'.  I assume that it is not a real concern since for a command line utility, we assume the user knows what they are downloading and its their responsibility. Let me know if I'm wrong here.

Thoughts? /cc @lidel

2022-10-05 00:24 UTC, BigLep commented
I haven't been following the details closely, but I know we have had security issues with tar issues over the years.  Can we make sure the security hardening is all in one place and shared across the stack (rather than copy and pasted)?

2022-10-05 09:16 UTC, hacdias commented
> I haven't been following the details closely, but I know we have had security issues with tar issues over the years. Can we make sure the security hardening is all in one place and shared across the stack (rather than copy and pasted)?

I definitely agree and I think it'd be better to just update this on [go-ipfs-files](https://github.com/ipfs/go-ipfs-files/). However, I also want to ensure that everyone agrees with the strategy. Right now, all files that would otherwise fall outside the root directory are forced to stay within the root directory. This does not keep the tree structure.

Yesterday during the colo @lidel mentioned that it could also be a great idea to just return an error and fail building the TAR. That is the behaviour of `ipfs get`, as `ipfs get` fetches a TAR and unpacks it . The unpacking fails if there are files that point outside the root directory. This error is triggered in [tar-utils](https://github.com/ipfs/tar-utils):

https://github.com/ipfs/tar-utils/blob/91e41e72cd61595a086c48862277c419a994d971/extractor.go#L189-L207

And also:

https://github.com/ipfs/tar-utils/blob/91e41e72cd61595a086c48862277c419a994d971/extractor.go#L156-L167

Instead of failing during the TAR unpacking, we can make it fail during the TAR creation, covering all cases where malicious TARs may be created. However, as @lidel mentioned yesterday, this may break someone else's use case (any idea?). But so would truncating the paths. Nowadays we always have CAR files where the user can always download the RAW, unmodified data if they please.

So two options:

1. Fail during creation.
2. Truncate file paths.

In either case, I will be updating the original TarWriter in https://github.com/ipfs/go-ipfs-files.

2022-10-05 12:54 UTC, lidel commented
* error is better than mutating directory tree – instead of mutating directory tree, error when any `../` goes beyond the `/ipfs/cid` 
  - error should note that relative UnixFS paths beyond `/ipfs/cid` root are not allowed for TAR, and suggest use of CAR instead
* create test fixtures for `/ipfs/cid/sub/../dir` (no error) and `/ipfs/cid/../dir` (should error) and include them in specs (https://github.com/ipfs/specs/pull/288)

2022-10-05 14:39 UTC, hacdias commented
Current things to do:

- [x] Update `TarWriter` to fail if there's UnixFS files pointing outside the root directory: https://github.com/ipfs/go-ipfs-files/pull/56 with tests.
- [ ] Create CAR fixtures
	- [ ] File points outside the root directory
	- [ ] File with relative path points somewhere inside the root directory
- [ ] Make tests
- [ ] Magic?

2022-10-06 11:40 UTC, hacdias commented
PR is ready for review. Please note that https://github.com/ipfs/go-ipfs-files/pull/56 needs to be merged first.

2022-10-07 07:15 UTC, hacdias commented
@lidel (cc @Jorropo) I updated the PR to manually close the connection if there is an error. This method should only work with HTTP/1.x connections, since the hijacker is not available for HTTP/2 connections: https://pkg.go.dev/net/http#Hijacker. 

In the scenario we are not able to hijack, and therefore manually close, the connection, we print the error to the client, corrupting the generated TAR file. That also leads to an error on the client side. I updated the tests accordingly.

<img width="242" alt="Screenshot 2022-10-07 at 08 56 53" src="https://user-images.githubusercontent.com/5447088/194486654-5d22cd28-6db7-474d-b5e5-84e4eac49890.png">

2022-10-10 09:25 UTC, hacdias commented
I have finished my self-review of this PR and https://github.com/ipfs/go-ipfs-files/pull/56.

@Jorropo I added you as a reviewer to have one more pair of eyes looking at this.

2022-10-10 12:30 UTC, hacdias commented
I finished self-reviewing this PR, fixed some issues and added some more tests. PRs that need review:

- https://github.com/ipfs/specs/pull/288
- https://github.com/ipfs/go-ipfs-files/pull/56
- This PR.

@Jorropo I added you as a reviewer to have one more pair of eyes looking at this.

2022-10-13 09:43 UTC, hacdias commented
Perhaps this PR should be merged only after https://github.com/ipfs/kubo/pull/9333 and its spec are solved because we also need to use that mechanism here.

2022-11-07 11:41 UTC, hacdias commented
The spec has been approved in the meeting: https://github.com/ipfs/specs/pull/288#pullrequestreview-1141490028

Is it possible to get some reviews here? /cc @lidel @Jorropo @guseggert

2022-11-08 10:26 UTC, hacdias commented
As per my conversation with @lidel yesterday, we decided to keep the existing behaviour for when there are errors while streaming the TAR. That is, we simply print the error (leading to a corrupt TAR file) and print a trailing header with the error. Decisions on how streaming errors should be handled will be worked on: https://github.com/ipfs/specs/pull/332 and https://github.com/ipfs/kubo/pull/9333.

2022-11-09 18:15 UTC, lidel approved these changes
Thank you @hacdias, let's include this in Kubo 0.17-rc1 (will merge after CI passes).

(pushed some cosmetic changes around Etag + added entry to changelog)

2022-11-09 18:20 UTC, merged