fix ipfs swarm peering crash in offline mode
ipfs/kubo pull request #9261
Opened 2022-09-09 23:37 UTC by aya

Fixes: #8699 #9247

2022-09-22 05:32 UTC, Jorropo requested changes
thx for your patch, it's mostly good, just there is a `node.IsOnline` field to know if a node is online. :slightly_smiling_face:

2022-09-22 05:32 UTC, Jorropo commented on core/commands/swarm.go
> +		if node.PeerHost == nil {
```suggestion
		if !node.IsOnline {
```

2022-09-22 05:32 UTC, Jorropo commented on core/commands/swarm.go
> +		if node.PeerHost == nil {
```suggestion
		if !node.IsOnline {
```

2022-09-22 05:32 UTC, Jorropo commented on core/commands/swarm.go
> +		if node.PeerHost == nil {
```suggestion
		if !node.IsOnline {
```

2022-09-22 11:45 UTC, aya commented
thx for your feedback, it's much simpler indeed :)
I updated the whole file with your recommendation in a separate commit, as I took inspiration for the fix from other lines using PeerHost instead of IsOnline.

2022-10-13 14:42 UTC, Jorropo approved these changes
LGTM, thx :tada:

2022-10-13 14:43 UTC, merged