docs: Swarm.AddrFilters ip address example fix
ipfs/kubo pull request #9386
Opened 2022-11-08 00:50 UTC by alx696

The current example `192.168.0.0/16` is wrong:

```
2022-11-08T08:47:41.660+0800	ERROR	core	core/builder.go:157	constructing the node: could not build arguments for function "github.com/ipfs/kubo/core/node".PeerWith.func1 (/home/m/go/pkg/mod/github.com/ipfs/kubo@v0.16.0/core/node/peering.go:29): failed to build *peering.PeeringService: could not build arguments for function "github.com/ipfs/kubo/core/node".Peering (/home/m/go/pkg/mod/github.com/ipfs/kubo@v0.16.0/core/node/peering.go:14): failed to build host.Host: could not build arguments for function "github.com/ipfs/kubo/core/node/libp2p".Host (/home/m/go/pkg/mod/github.com/ipfs/kubo@v0.16.0/core/node/libp2p/host.go:40): could not build value group []config.Option[group="libp2p"]: received non-nil error from function "github.com/ipfs/kubo/core/node/libp2p".AddrFilters.func1 (/home/m/go/pkg/mod/github.com/ipfs/kubo@v0.16.0/core/node/libp2p/addrs.go:14): incorrectly formatted address filter in config: 192.168.0.0/16
```

`/ip4/192.168.0.0/ipcidr/16` is correct.

2022-11-08 01:00 UTC, Jorropo requested changes
Thx but, this isn't wrong, this is using usual CIDR syntax.

As this is just an example of what it does, I think it is better to stay that way because this is understandable by people that doesn't fully grasp multiaddr yet,
if you want you can add an example of multiaddr syntax.

2022-11-08 01:15 UTC, alx696 commented
> Thx but, this isn't wrong, this is using usual CIDR syntax.
> 
> As this is just an example of what it does, I think it is better to stay that way because this is understandable by people that doesn't fully grasp multiaddr yet, if you want you can add an example of multiaddr syntax.

Sorry for my inaccurate description. A directly usable example might be better for starter. In this way, the configuration can be completed even if the professional knowledge is insufficient.

2022-11-08 01:15 UTC, closed without merging

2022-11-08 01:17 UTC, Jorropo commented
> Sorry for my inaccurate description. A directly usable example might be better for starter.

I agree, but I would like to keep the existing thing for thoses who know it, an example of how this could look like:

> (e.g., `192.168.0.0/16` or in mutladdr form `/ip4/192.168.0.0/ipcidr/16`)

2023-02-21 17:56 UTC, decentralgabe commented
This should be re-opened and merged. The current example is confusing and not helpful!

2023-02-21 18:13 UTC, Jorropo commented
> The current example is confusing and not helpful!

I overlooked this, sorry.

One possible solution would be to edit this paragraph to be:
> ```diff
> -preventing dials to all non-routable IP addresses (e.g., `192.168.0.0/16`) but
> +preventing dials to all non-routable IP addresses (e.g., `/ip4/192.168.0.0/ipcidr/16`
> +which is the multiaddress representation of `192.168.0.0/16`) but
> ```

However I think this is a little weird because in this sentence:
> (e.g., `192.168.0.0/16`) 

Refers to:
> non-routable IP addresses

Which refers to stuff you would want to add into the config, the connection between `192.168.0.0/16` and `/ip4/192.168.0.0/ipcidr/16` seems rather indirect to me.

So an other solution could be to add a new example paragraph showing you the syntax or a list of examples.
I don't have a preference between boths.

If someone opens a PR implementing either of both solution I'll merge it (or try something else if you think you have a better idea). :slightly_smiling_face:

2023-02-22 18:48 UTC, decentralgabe commented
Hi @Jorropo I opened https://github.com/ipfs/kubo/pull/9661