WIP: update go-libp2p to v0.26
ipfs/kubo pull request #9656
Opened 2023-02-18 22:14 UTC by marten-seemann

2023-02-22 11:58 UTC, lidel requested changes
We need to add  configuration option (Flag) `Swarm.RelayService.Limit.Enabled` that is 
- true by default (implicit limits), but 
- when explicitly set to `false` ensures we initialize RelayService with [WithInfiniteLimits from this PR](https://github.com/libp2p/go-libp2p/pull/2125)

2023-02-22 22:19 UTC, marten-seemann commented
> We need to add configuration option (Flag) `Swarm.RelayService.FooLimitEnabled` that is
> 
> * true by default (implicit limits), but
> * when explicitly set to `false` ensures we initialize RelayService with [WithInfiniteLimits from this PR](https://github.com/libp2p/go-libp2p/pull/2125)

This is unrelated to this PR, if I understand correctly. Kubo didn't have an option to enable a v1 relay - that's why we introduced the [relay daemon](https://github.com/libp2p/go-libp2p-relay-daemon).

2023-02-22 22:21 UTC, lidel commented
@marten-seemann ack, I'll add config for https://github.com/libp2p/go-libp2p/pull/2125 in a separate PR, after this one is merged.

2023-02-23 08:29 UTC, hacdias commented
@marten-seemann can you rebase on top of the latest master? I'll take a look in a bit.

2023-02-23 08:29 UTC, marten-seemann commented
Updated to the official v0.26.0 release. This should be ready to go now :)

2023-02-23 09:00 UTC, hacdias commented
Things still to fix (I will take a look, but may take longer time as I'm not very knowledgeable about this codebase):

- Remove Circuit V1 Relay tests from [interop](https://github.com/ipfs/interop/tree/master/test/circuit/v1) as it was [removed](https://github.com/libp2p/go-libp2p/releases/tag/v0.26.0).
- Update sharness tests with the new metrics included by go-libp2p v0.26.0
- kad-dht tests still failing (hoping that will be fixed with #9663)

2023-02-23 09:03 UTC, marten-seemann commented
> * [ ]  Update sharness tests with the new metrics included by go-libp2p v0.26.0

Not my business, but I've never understood why Kubo would make any assertions on the metrics exposed by libp2p. Maybe consider filtering out all `libp2p_` metrics?

2023-02-23 09:04 UTC, hacdias commented
@marten-seemann yeah, definitely. I was not insinuating you should make the changes. I will take a look at that.

2023-02-23 10:41 UTC, hacdias commented
Waiting for the interop tests to be fixed and released: https://github.com/ipfs/interop/pull/592

/cc @lidel @Jorropo

2023-02-24 09:33 UTC, hacdias approved these changes

2023-02-24 09:34 UTC, merged