fix: do not use b58mh peer id for ipns test
ipfs/kubo pull request #9785
Opened 2023-03-31 12:33 UTC by hacdias

2023-04-05 17:12 UTC, lidel requested changes

2023-04-05 17:12 UTC, lidel commented on test/cli/gateway_test.go
> +		"PeerID": peer.ToCid(node.PeerID()).String(),
make this and all other places base36, so users are not confused by different CID for IPNS Record.

(base36 is the only thing that fits in a DNS label, and is already used by `ipfs name` commands

2023-04-11 09:19 UTC, hacdias commented
⚠️ Unrelated sharness tests failing: https://filecoinproject.slack.com/archives/C03FW2RKK5Y/p1681203610104569

2023-04-24 06:02 UTC, hacdias commented
Sharness and interop/go-ipfs-http-client failing due to external reasons to this PR.

2023-05-16 11:08 UTC, lidel approved these changes
Rebased, lgtm.

2023-05-16 11:09 UTC, merged