fix: print rcmgr to logger
ipfs/kubo pull request #9922
Opened 2023-06-08 09:59 UTC by Jorropo

This was proposed by @lidel as an easy alternative to #9826.
It helps by trimming down the wall of text:
```console
$ ipfs daemon
Initializing daemon...
Kubo version: 0.21.0-dev
Repo version: 14
System version: amd64/linux
Golang version: go1.19.10
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/127.0.0.1/udp/4001/quic
Swarm listening on /ip4/127.0.0.1/udp/4001/quic-v1
Swarm listening on /ip4/127.0.0.1/udp/4001/quic-v1/webtransport/certhash/uEiBxxxS3-F4l3cdUMusi6JDe4me_I8_x0HwwCVC7dty6tw/certhash/uEiDoGHKF-YokgamslR4CqcVPFtVvKGVz1KoW26Xqeis9aw
Swarm listening on /ip4/172.17.0.1/tcp/4001
Swarm listening on /ip4/172.17.0.1/udp/4001/quic
Swarm listening on /ip4/172.17.0.1/udp/4001/quic-v1
Swarm listening on /ip4/172.17.0.1/udp/4001/quic-v1/webtransport/certhash/uEiBxxxS3-F4l3cdUMusi6JDe4me_I8_x0HwwCVC7dty6tw/certhash/uEiDoGHKF-YokgamslR4CqcVPFtVvKGVz1KoW26Xqeis9aw
Swarm listening on /ip4/192.168.1.31/tcp/4001
Swarm listening on /ip4/192.168.1.31/udp/4001/quic
Swarm listening on /ip4/192.168.1.31/udp/4001/quic-v1
Swarm listening on /ip4/192.168.1.31/udp/4001/quic-v1/webtransport/certhash/uEiBxxxS3-F4l3cdUMusi6JDe4me_I8_x0HwwCVC7dty6tw/certhash/uEiDoGHKF-YokgamslR4CqcVPFtVvKGVz1KoW26Xqeis9aw
Swarm listening on /ip6/204:e3e5:ec57:9482:3f92:bf4d:74bf:cfed/tcp/4001
Swarm listening on /ip6/204:e3e5:ec57:9482:3f92:bf4d:74bf:cfed/udp/4001/quic
Swarm listening on /ip6/204:e3e5:ec57:9482:3f92:bf4d:74bf:cfed/udp/4001/quic-v1
Swarm listening on /ip6/204:e3e5:ec57:9482:3f92:bf4d:74bf:cfed/udp/4001/quic-v1/webtransport/certhash/uEiBxxxS3-F4l3cdUMusi6JDe4me_I8_x0HwwCVC7dty6tw/certhash/uEiDoGHKF-YokgamslR4CqcVPFtVvKGVz1KoW26Xqeis9aw
Swarm listening on /ip6/2a01:cb05:806e:900:50b0:74cc:c3cd:7105/tcp/4001
Swarm listening on /ip6/2a01:cb05:806e:900:50b0:74cc:c3cd:7105/udp/4001/quic
Swarm listening on /ip6/2a01:cb05:806e:900:50b0:74cc:c3cd:7105/udp/4001/quic-v1
Swarm listening on /ip6/2a01:cb05:806e:900:50b0:74cc:c3cd:7105/udp/4001/quic-v1/webtransport/certhash/uEiBxxxS3-F4l3cdUMusi6JDe4me_I8_x0HwwCVC7dty6tw/certhash/uEiDoGHKF-YokgamslR4CqcVPFtVvKGVz1KoW26Xqeis9aw
Swarm listening on /ip6/2a01:cb05:806e:900:5551:169f:7e3:5e59/tcp/4001
Swarm listening on /ip6/2a01:cb05:806e:900:5551:169f:7e3:5e59/udp/4001/quic
Swarm listening on /ip6/2a01:cb05:806e:900:5551:169f:7e3:5e59/udp/4001/quic-v1
Swarm listening on /ip6/2a01:cb05:806e:900:5551:169f:7e3:5e59/udp/4001/quic-v1/webtransport/certhash/uEiBxxxS3-F4l3cdUMusi6JDe4me_I8_x0HwwCVC7dty6tw/certhash/uEiDoGHKF-YokgamslR4CqcVPFtVvKGVz1KoW26Xqeis9aw
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /ip6/::1/udp/4001/quic
Swarm listening on /ip6/::1/udp/4001/quic-v1
Swarm listening on /ip6/::1/udp/4001/quic-v1/webtransport/certhash/uEiBxxxS3-F4l3cdUMusi6JDe4me_I8_x0HwwCVC7dty6tw/certhash/uEiDoGHKF-YokgamslR4CqcVPFtVvKGVz1KoW26Xqeis9aw
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/127.0.0.1/udp/4001/quic
Swarm announcing /ip4/127.0.0.1/udp/4001/quic-v1
Swarm announcing /ip4/127.0.0.1/udp/4001/quic-v1/webtransport/certhash/uEiBxxxS3-F4l3cdUMusi6JDe4me_I8_x0HwwCVC7dty6tw/certhash/uEiDoGHKF-YokgamslR4CqcVPFtVvKGVz1KoW26Xqeis9aw
Swarm announcing /ip4/192.168.1.31/tcp/4001
Swarm announcing /ip4/192.168.1.31/udp/4001/quic
Swarm announcing /ip4/192.168.1.31/udp/4001/quic-v1
Swarm announcing /ip4/192.168.1.31/udp/4001/quic-v1/webtransport/certhash/uEiBxxxS3-F4l3cdUMusi6JDe4me_I8_x0HwwCVC7dty6tw/certhash/uEiDoGHKF-YokgamslR4CqcVPFtVvKGVz1KoW26Xqeis9aw
Swarm announcing /ip6/2a01:cb05:806e:900:50b0:74cc:c3cd:7105/tcp/4001
Swarm announcing /ip6/2a01:cb05:806e:900:50b0:74cc:c3cd:7105/udp/4001/quic
Swarm announcing /ip6/2a01:cb05:806e:900:50b0:74cc:c3cd:7105/udp/4001/quic-v1
Swarm announcing /ip6/2a01:cb05:806e:900:50b0:74cc:c3cd:7105/udp/4001/quic-v1/webtransport/certhash/uEiBxxxS3-F4l3cdUMusi6JDe4me_I8_x0HwwCVC7dty6tw/certhash/uEiDoGHKF-YokgamslR4CqcVPFtVvKGVz1KoW26Xqeis9aw
Swarm announcing /ip6/::1/tcp/4001
Swarm announcing /ip6/::1/udp/4001/quic
Swarm announcing /ip6/::1/udp/4001/quic-v1
Swarm announcing /ip6/::1/udp/4001/quic-v1/webtransport/certhash/uEiBxxxS3-F4l3cdUMusi6JDe4me_I8_x0HwwCVC7dty6tw/certhash/uEiDoGHKF-YokgamslR4CqcVPFtVvKGVz1KoW26Xqeis9aw
RPC API server listening on /ip4/127.0.0.1/tcp/5001
WebUI: http://127.0.0.1:5001/webui
Gateway server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready
git ^C
Received interrupt signal, shutting down...
```

2023-06-08 12:06 UTC, hacdias approved these changes

2023-06-08 12:07 UTC, hacdias requested changes
Sharness is failing `ipfs daemon output looks good`.

2023-06-08 15:34 UTC, Jorropo commented
> Sharness is failing

I know I didn't bothered touching sharness before people tell me it's acceptable.

2023-06-12 13:52 UTC, lidel reviewed
@Jorropo  approach lgtm, just fix sharness :-))

2023-06-12 14:00 UTC, hacdias approved these changes

2023-06-12 14:25 UTC, merged